name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  create-gh-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Generate CHANGELOG.md
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          CUR_TAG=${GITHUB_REF_NAME}
          LOG_FORMAT='- **`%h`** %s by @%cn'
          REPO_URL="https://github.com/${{ github.repository }}"

          if [ -z "$PREV_TAG" ]; then
            echo "## Initial Release" > CHANGELOG.md
            echo "" >> CHANGELOG.md
            git log --reverse --pretty=format:"$LOG_FORMAT" >> CHANGELOG.md
          else
            echo "## Changelog $PREV_TAG..$CUR_TAG" > CHANGELOG.md
            echo "" >> CHANGELOG.md
            git log $PREV_TAG..HEAD --reverse --pretty=format:"$LOG_FORMAT" >> CHANGELOG.md
            echo "" >> CHANGELOG.md
            echo "" >> CHANGELOG.md
            echo "**Full Changelog**: [\`$PREV_TAG..$CUR_TAG\`]($REPO_URL/compare/$PREV_TAG...$CUR_TAG)" >> CHANGELOG.md
          fi
      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          generate_release_notes: false
          body_path: CHANGELOG.md
          files: |
            LICENSE

  build-and-push-docker-image:
    needs: create-gh-release
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v6
      - name: Create .env
        run: |
          echo "WEB_HOST=${{ secrets.WEB_HOST }}" >> .env
          echo "API_HOST=${{ secrets.API_HOST }}" >> .env
          echo "INTERNAL_API_KEY=${{ secrets.INTERNAL_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_WEB_HOST=${{ secrets.NEXT_PUBLIC_WEB_HOST }}" >> .env
          echo "NEXT_PUBLIC_API_HOST=${{ secrets.NEXT_PUBLIC_API_HOST }}" >> .env
          echo "NEXT_PUBLIC_ASSETS_HOST=${{ secrets.NEXT_PUBLIC_ASSETS_HOST }}" >> .env
          echo "NEXT_PUBLIC_GITHUB_URL=${{ secrets.NEXT_PUBLIC_GITHUB_URL }}" >> .env
          echo "NEXT_PUBLIC_DISCORD_URL=${{ secrets.NEXT_PUBLIC_DISCORD_URL }}" >> .env
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          IMAGE=ghcr.io/${{ github.repository }}:$VERSION
          docker build -t $IMAGE .
          docker push $IMAGE
